name : CI Pipeline - DEV
on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  GIT__BRANCH      : 'dev'
  RELEASE_TYPE     : 'minor'
  PACKAGE_NAME     : 'myfeeds_ai'

jobs:

  run-tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "run-tests"
        uses: ./.github/actions/run-tests

  run-qunit-tests:
    name: Run QUnit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run QUnit Tests
        uses: ./.github/actions/run-qunit-tests
        with:
          node-version: '22.4.1'

  increment-tag:
    name: Increment Tag - DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type: ${{ env.RELEASE_TYPE }}
    needs:
      - run-tests
      - run-qunit-tests

  publish-to-pypi:
    if: False
    name: "Publish to: PYPI"
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Git Update Current Branch
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

      - name: publish-to-pypi
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pypi__publish@dev
    needs:
      - increment-tag